Automatically renew TLS certificates
ChameleonCloud/portal-camino pull request #8
Opened 2022-10-10 22:57 UTC by super-cooper

This change adds a new certbot Docker service which automatically attempts to renew the certs every day at 10 AM. nginx is reloaded every day by a cronjob on the host system. The only way to reload nginx is to send `SIGHUP` to its process, so certbot is unfortunately unable to do this without access to the Docker socket.

Certbot uses webroot challenges, and as such, nginx is configured to properly respond to Let's Encrypt's challenge requests.

2022-10-10 22:59 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automate Portal TLS certificate renewal](https://trello.com/c/UjaGiLvr/2790-automate-portal-tls-certificate-renewal)

2022-10-10 23:12 UTC, msherman64 commented
If we need a cronjob on the host system anyway, it's probably best to combine it with the certbot one.
Ideally again we only reload nginx when the cert is renewed, instead of once/twice per day.

Especially given that `/etc/letsencrypt` and `/var/www/certbot` are mounted in the nginx container, can we just run certbot on the host with `--deploy-hook docker restart nginx`?

2022-10-11 15:12 UTC, msherman64 requested changes
As in the comments, if we need a recurring task on the host anyway, it seems best to leverage certbot's deploy hook to only restart nginx on an actual change to the cert.

2022-10-11 15:12 UTC, msherman64 commented on conf/certbot/certbot.Dockerfile
> +ENTRYPOINT ["crond", "&&", "tail", "-f", "/var/log/cron.log"]
does `&&` work in an entrypoint?

Cron can be run in foreground with `cron -f`

2022-10-11 15:14 UTC, super-cooper commented on conf/certbot/certbot.Dockerfile
> +ENTRYPOINT ["crond", "&&", "tail", "-f", "/var/log/cron.log"]
It does work. Running cron in the foreground was not producing logs, so I switched to this method. I will look into putting this on the host instead.

2022-10-11 15:30 UTC, super-cooper commented
The cronjob from the certbot image has been moved to host cron, and the renewal hook has been put into `/etc/letsencrypt/renewal-hooks/post/reload-nginx.sh`.

2022-10-12 20:18 UTC, msherman64 approved these changes
Looks good to me! Can you add the extra info about certbot to the Readme?
Otherwise, looks good to merge.

2022-10-12 20:36 UTC, super-cooper commented
> Can you add the extra info about certbot to the Readme?
Done

2022-10-12 20:38 UTC, merged